// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5aSFUX6v5Nh946ryguU28wrFnUiiVCdk',
    appId: '1:362070731545:web:1813abb86a9a151a9d7388',
    messagingSenderId: '362070731545',
    projectId: 'expense-planner-4455c',
    authDomain: 'expense-planner-4455c.firebaseapp.com',
    storageBucket: 'expense-planner-4455c.firebasestorage.app',
    measurementId: 'G-5FN8YGX2CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62B3y4cbx6uyLrK4N_U_RRJJiOMttjs8',
    appId: '1:362070731545:android:9d57de5415c5faeb9d7388',
    messagingSenderId: '362070731545',
    projectId: 'expense-planner-4455c',
    storageBucket: 'expense-planner-4455c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7OTKNyx-z86PAkBCOH5QK7esYqK0i3KQ',
    appId: '1:362070731545:ios:db692b6209c00ba19d7388',
    messagingSenderId: '362070731545',
    projectId: 'expense-planner-4455c',
    storageBucket: 'expense-planner-4455c.firebasestorage.app',
    iosBundleId: 'com.example.expensePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7OTKNyx-z86PAkBCOH5QK7esYqK0i3KQ',
    appId: '1:362070731545:ios:db692b6209c00ba19d7388',
    messagingSenderId: '362070731545',
    projectId: 'expense-planner-4455c',
    storageBucket: 'expense-planner-4455c.firebasestorage.app',
    iosBundleId: 'com.example.expensePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5aSFUX6v5Nh946ryguU28wrFnUiiVCdk',
    appId: '1:362070731545:web:6fc870ee9a1525a79d7388',
    messagingSenderId: '362070731545',
    projectId: 'expense-planner-4455c',
    authDomain: 'expense-planner-4455c.firebaseapp.com',
    storageBucket: 'expense-planner-4455c.firebasestorage.app',
    measurementId: 'G-2QKLY1H454',
  );
}
